name: telesrv
version: 1.0_BETA_1
main: com.telesrv.Telesrv
api-version: 1.20
description: Telesrv - Connect Minecraft, Telegram & Discord
author: PersiaNerd
website: https://persianerd.ir
softdepend:
  - DiscordSRV
commands:
  telesrv:
    description: Telesrv Main Command
    usage: /telesrv
    permission: telesrv.admin
permissions:
  telesrv.admin:
    description: Allows access to telesrv admin commands
    default: op
